### ISSUE TITLE
Android multiple text renderer issue (non-issue)

### ISSUE THREAD

**Issue by DonWono** [mimetic/corona-textrender#5]
I'm using the textrender to display messages in my app, and display url links which the user can press. When there are multiple messages, the textrenderer seems to have an issue, and displays the url link in all the messages.

**Comment by mimetic** [comment]
Hey, I'll look into this. Can you send me any demo files, esp. the exact text you are trying to render?
Thanks
-David

> On Apr 7, 2016, at 3:25 AM, DonWono notifications@github.com wrote:
> 
> I'm using the textrender to display messages in my app, and display url links which the user can press. When there are multiple messages, the textrenderer seems to have an issue, and displays the url link in all the messages.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub https://github.com/mimetic/corona-textrender/issues/5

...David I. Gross...

LinkedIn: http://www.linkedin.com/in/davidigross
Photo Portfolio site: http://www.davidgrossphoto.com/
Inside-Outside: http://insideoutsideproject.com/
Mimetic Books: http://www.mimetic.com/
Mimetic Galleries: http://info.mimetic.com/

Email: davidigross@me.com
Mobile (direct) : +1 (408) 464-6182 (Pacific Time)
Home (direct) : +1 (408) 239-4488
Travel Tel: +1 (408) 827-8557 (GMT -8:00)
Fax : +1 (831) 618-8791
Skype : davidgross

CONFIDENTIALITY NOTE:
This e-mail and any attachments or previous e-mail messages attached to it are confidential and may be protected by legal privilege.  If you are not the intended recipient, you are hereby notified that any disclosure, distribution, or copying of this message, or any attachment, is prohibited.  If you have received this message in error, please notify the original sender immediately by returning it to the sender and delete this copy, along with any attachments, from your computer without reading or saving it in any manner.  Thank you for your cooperation.

**Comment by DonWono** [comment]
Hi.
   I actually closed the issue because it was my fault. I had the cache turned on. After I turned the cachedb off, it fixed the issue. Thank you very much.

All the best,
Donald
